### PR TITLE
Add tremor link to README.md

### PR DESCRIPTION
**Pull request by christopherkindl**
Add Tremor link in open-source section

### CODE REVIEW

**Comment by christopherkindl** [comment]
Hi @steven-tey, many thanks for using Tremor again - Would be awesome if you could add the link in the README 🙏

**Comment by steven-tey** [comment]
Thank you! So sorry for missing that before 🙏

**Comment by steven-tey** [comment]
Also added them in the guide too: 
CleanShot 2023-07-05 at 19 01 51
CleanShot 2023-07-05 at 19 01 56

**Comment by steven-tey** [comment]
Again, sorry for missing this, had too many things going on 😓

**Comment by christopherkindl** [comment]
Oh wow, thanks for that from the entire Tremor team!!

**Pull request merged**
