### PR TITLE
Fix settings inputs

### PR DESCRIPTION
**Pull request by iuzn**
### Problem:
I got an error caused by the inputs in `/site/[id]/settings` directories. Some inputs are not editable. Some inputs are also misconfigured.

The following error is received when trying to edit.  This screenshot below is taken from `https://app.vercel.pub/site/[id]/settings`

image

### Solution

- Added ref attribute to some inputs in site settings
- Removed unused event parameter in onInput
- Removed unused data parameter in setData

_Best regards,
Ibrahim Uzun_

### CODE REVIEW

**Comment by ehowey** [comment]
Just popping in to say that I saw some weird errors with the settings inputs as well. I haven't gone through them all, but chiming in to say that something does seem off here.

**Comment by steven-tey** [comment]
Thanks a lot for your help with this @iuzn! I apologize for the type errors & misconfigured inputs, I was a Typescript noob when I first built this 😅

Will be merging this PR now!

Related: 
- https://github.com/vercel/platforms/pull/105
- https://github.com/vercel/platforms/issues/101

**Review by steven-tey — APPROVED** [review]
LGTM!

**Comment by iuzn** [comment]
Thanks for approving the pull request. Everything will be better 🥳

**Pull request merged**
