### PR TITLE
Migrating `/pages` to `/app`

### PR DESCRIPTION
**Pull request by steven-tey**

### CODE REVIEW

**Comment by slavakurilyak** [comment]
It's a good idea to migrate the `/pages` directory to the `/app` directory in a Next.js app in order to use the latest features of Next.js v13. It's a smart move to finalize this update in the new year!

**Comment by steven-tey** [comment]
@slavakurilyak we actually completed the migration for client sites (`/_sites`) but we're gonna revert it and leave it on this branch until the `app` directory is stable (out of beta) :)

**Comment by jasonsilberman** [comment]
Hi @steven-tey, have you had any chance to make progress finishing the migration of this project to the app dir?

I'd love a fully baked example of how all of these new next.js features work together!

**Comment by samratarmas** [comment]
Hello @steven-tey I am coming straight from reading the [NextJs 13.4 release blog](https://nextjs.org/blog/next-13-4) to comment over here :)

Very excited about the stable release of app router. NextJs docs is now recommending new apps to start with the app directory. Are you going to push this now that 13.4 is live or are there still some other hindrances to completing the migration?

**Comment by ajdiyassin** [comment]
Any hopes to get this merged since app dir is now stable?

**Comment by steven-tey** [comment]
Hey @slavakurilyak @fredericrous @jasonsilberman @samratarmas @ajdiyassin! Apologies for the delay here, but we're finally finishing the swing on the App Router migration via #221! <picture data-single-emoji=":cele-cry:" title=":cele-cry:">:cele-cry:</picture> 

Will be closing this PR now since it uses a lot of the beta stuff that has since been deprecated, so feel free to follow along the new PR! I'm going to outline all the TODOs so y'all can follow along the progress! ETA for that PR merging into main is in the next week or two! <picture data-single-emoji=":fingers-crossed-bart:" title=":fingers-crossed-bart:">:fingers-crossed-bart:</picture>

**Pull request closed without merging**
