### PR TITLE
App Router Migration

### PR DESCRIPTION
**Pull request by steven-tey**
This PR migrates the Platforms Starter Kit to the App Router (finally 🥳)

TODO list:
- [x] Migrate client sites to App Router
- [x] Custom fonts for sites (glimpse into how custom themes would work)
- [x] Optional feature to auto-redirect subdomain to the custom domain if the custom domain exists
- [x] [`unstable_cache`](https://nextjs.org/docs/app/api-reference/functions/revalidateTag) implementation
- [x] Dynamic OG images for post pages ([sneak peak](https://share.cleanshot.com/1NDnjfRB))
- [x] Migrate database to Vercel Postgres
- [x] [Notion-like WYSYWIG editor with AI autocompletions](https://github.com/steven-tey/novel) ([check out the launch](https://twitter.com/steventey/status/1669762868416512000)) <picture data-single-emoji=":eyeses:" title=":eyeses:">:eyeses:</picture> 
- [x] Replace CRUD API routes with Server Actions
- [x] [`revalidateTag`](https://nextjs.org/docs/app/api-reference/functions/revalidateTag) implementation
- [x] Image uploads for site & post thumbnails
- [x] Migrate app.vercel.pub to App Router
- [x] Mobile responsive
- [x] Empty states

### CODE REVIEW

**Comment by samratarmas** [comment]
Super excited!

**Comment by AliMejbar** [comment]
FINALLY !

**Comment by korabh** [comment]
Hey @steven-tey! Just wanted to check if you plan to merge this pull request during this week? Thanks!

**Comment by steven-tey** [comment]
@korabh update: slight delay – new ETA is before the end of next week! 🙏

**Comment by korabh** [comment]
> @korabh update: slight delay – new ETA is before the end of next week!

Amazing! Thank you so much for the update!

**Comment by SuttonJack** [comment]
If it's any help, [here's](https://github.com/SuttonJack/multi-tenant-tag-revalidation/tree/main) the approach that I used for `revalidateTag` when I migrated a similar app  😄

**Comment by steven-tey** [comment]
Thanks a lot for sharing @SuttonJack 🤩

**Comment by steven-tey** [comment]
Sneak peek 👀

CleanShot 2023-06-23 at 09 45 42

**Comment by VictorCalderon** [comment]
Hey @steven-tey, I tried the repo today locally, I can wait for its release 🤩. 

I noticed during the migration to Vercel Postgres (a4a9a647f562f16faaf2ea65c2f7c4e8fd218d38) you left .env.example with MySQL variables for DATABASE_URL but changed prisma/schema.prisma to Vercel Postgres. Very minor issue.

**Comment by steven-tey** [comment]
The end of an era <picture data-single-emoji=":proud:" title=":proud:">:proud:</picture> 
 
https://github.com/vercel/platforms/assets/28986134/2b0aa7b3-ffa8-4995-9e1f-cf128f57d007

**Comment by smotched** [comment]
@steven-tey and it already auth selected what you should delete next!

**Comment by VictorCalderon** [comment]
Can't wait for this to get merged! Let's goo 🚀🚀🚀

**Comment by steven-tey** [comment]
<picture data-single-emoji=":lfg-intense:" title=":lfg-intense:">:lfg-intense:</picture> <picture data-single-emoji=":lfg-intense:" title=":lfg-intense:">:lfg-intense:</picture> <picture data-single-emoji=":lfg-intense:" title=":lfg-intense:">:lfg-intense:</picture> <picture data-single-emoji=":lfg-intense:" title=":lfg-intense:">:lfg-intense:</picture> <picture data-single-emoji=":lfg-intense:" title=":lfg-intense:">:lfg-intense:</picture> <picture data-single-emoji=":lfg-intense:" title=":lfg-intense:">:lfg-intense:</picture> <picture data-single-emoji=":lfg-intense:" title=":lfg-intense:">:lfg-intense:</picture> <picture data-single-emoji=":lfg-intense:" title=":lfg-intense:">:lfg-intense:</picture> <picture data-single-emoji=":lfg-intense:" title=":lfg-intense:">:lfg-intense:</picture> <picture data-single-emoji=":lfg-intense:" title=":lfg-intense:">:lfg-intense:</picture> <picture data-single-emoji=":lfg-intense:" title=":lfg-intense:">:lfg-intense:</picture>

**Comment by steven-tey** [comment]
...aaaand we broke it <picture data-single-emoji=":happy-cry:" title=":happy-cry:">:happy-cry:</picture> 

Debugging <picture data-single-emoji=":eye-twitch:" title=":eye-twitch:">:eye-twitch:</picture> 

CleanShot 2023-06-29 at 10 57 52

**Comment by steven-tey** [comment]
Fixed!! 

CleanShot 2023-06-29 at 11 27 52

**Comment by samratarmas** [comment]
> ...aaaand we broke it :happy-cry:
> 
> Debugging :eye-twitch:
> 
> CleanShot 2023-06-29 at 10 57 52

Looks like demo.vercel.pub still has 404

**Comment by steven-tey** [comment]
@samratarmas thanks for the headsup, looking into it! 🙏

**Comment by nukkerone** [comment]
@steven-tey  I think there's hardcoded domain ref in the middleware. 

image

**Pull request merged**
